# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai-torchgeo',
                'doc_host': 'https://butchland.github.io',
                'git_url': 'https://github.com/butchland/fastai-torchgeo',
                'lib_path': 'fastai_torchgeo'},
  'syms': {'fastai_torchgeo.core': {'fastai_torchgeo.core.foo': ('core.html#foo', 'fastai_torchgeo/core.py')}}}
