# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fastai-torchgeo',
                'doc_host': 'https://butchland.github.io',
                'git_url': 'https://github.com/butchland/fastai-torchgeo',
                'lib_path': 'fastai_torchgeo'},
  'syms': { 'fastai_torchgeo.core': { 'fastai_torchgeo.core.GeoTensorImage': ('core.html#geotensorimage', 'fastai_torchgeo/core.py'),
                                      'fastai_torchgeo.core.GeoTensorImage.__init__': ( 'core.html#geotensorimage.__init__',
                                                                                        'fastai_torchgeo/core.py'),
                                      'fastai_torchgeo.core.GeoTensorImage.__repr__': ( 'core.html#geotensorimage.__repr__',
                                                                                        'fastai_torchgeo/core.py'),
                                      'fastai_torchgeo.core.GeoTensorImage.create': ( 'core.html#geotensorimage.create',
                                                                                      'fastai_torchgeo/core.py'),
                                      'fastai_torchgeo.core.load_tif': ('core.html#load_tif', 'fastai_torchgeo/core.py'),
                                      'fastai_torchgeo.core.open_tif': ('core.html#open_tif', 'fastai_torchgeo/core.py'),
                                      'fastai_torchgeo.core.show': ('core.html#show', 'fastai_torchgeo/core.py')},
            'fastai_torchgeo.data': {'fastai_torchgeo.data.GeoImageBlock': ('data.html#geoimageblock', 'fastai_torchgeo/data.py')}}}
