# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data.ipynb.

# %% auto 0
__all__ = ['GeoImageBlock']

# %% ../nbs/01_data.ipynb 5
import fastai.vision.all as fv
from fastai_torchgeo.core import GeoTensorImage
from functools import partial

# %% ../nbs/01_data.ipynb 6
def GeoImageBlock(chnls_first=True):
    return fv.TransformBlock(type_tfms=partial(GeoTensorImage.create,chnls_first=chnls_first))
                             
